# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'здание',
                'verbose_name_plural': 'здания',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='material_for_build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buildings_can_be_build', to='core.Material'),
        ),
        migrations.AddField(
            model_name='building',
            name='materials_produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buildings_can_produce', to='core.Material'),
        ),
    ]
